### PR TITLE
Allow `Browser::click()` to work with css selector

### PR DESCRIPTION
**Pull request by Nyholm**
I want to be able to click on anything. We have some weird javascript that hide away a checkbox...

This only support selecting an element by ID. I am not sure how to implement it better.

### CODE REVIEW

**Comment by Nyholm** [comment]
Woho! I found out how to use CSS selectors =)

**Comment by kbond** [comment]
I think I'd prefer to merge into the click method if you don't mind.

**Comment by Nyholm** [comment]
Sure!

**Comment by kbond** [comment]
Thanks @Nyholm! Released in [v0.8.0](https://github.com/zenstruck/browser/releases/tag/v0.8.0).

**Comment by Nyholm** [comment]
Awesome. Thank you for the quick response!

**Pull request merged**
